PT-7355: Add mutation for company registration
VirtoCommerce/vc-module-profile-experience-api pull request #12
Opened 2022-05-23 13:27 UTC by einlied753

## Description
Add mutation for company registration and notification
## References
### QA-test:
### Jira-link:
 https://virtocommerce.atlassian.net/browse/PT-7355
 https://virtocommerce.atlassian.net/browse/PT-7386
### Artifact URL:

2022-05-23 15:59 UTC, Vectorfield4 requested changes

2022-05-23 15:59 UTC, Vectorfield4 commented on src/VirtoCommerce.ProfileExperienceApiModule.Data/Aggregates/RegisterCompanyAggregate.cs
> +    public class RegisterCompanyAggregate
```suggestion
    public class RegisterCompanyResult
```

2022-05-23 15:59 UTC, Vectorfield4 commented on src/VirtoCommerce.ProfileExperienceApiModule.Data/Aggregates/RegisterCompanyAggregate.cs
> +        public virtual ApplicationUser Account { get; set; }
Do we really need this model here?

2022-05-23 15:59 UTC, Vectorfield4 commented on src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterCompanyCommand.cs
> +        public ApplicationUser Account { get; set; }
Do we really need this model here?

2022-05-23 15:59 UTC, Vectorfield4 commented on src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterCompanyCommandHandler.cs
> +            try
Use `CancellationToken` to implement rollback flow, remove try..catch and unnecessary `Exceptions`. 
Pseudocode:
```
await RegisterCompanyAsync(cancellationToken);
if (cancellationToken.IsCancelled)
    await RollBackMembersCreationAsync();
```

2022-05-23 15:59 UTC, Vectorfield4 commented on src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterCompanyCommandHandler.cs
> +                aggregate.Account = account;
Do we really need all data from the account?

2022-05-23 15:59 UTC, Vectorfield4 commented on src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterCompanyCommandHandler.cs
> +        private async Task<IdentityResult> CreateAccountAsync(ApplicationUser account)
Move out from to a service.

2022-05-23 15:59 UTC, Vectorfield4 commented on src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterCompanyCommandHandler.cs
> +        }
No reason for awaiting here.
```suggestion
        private Task SetDynamicPropertiesAsync(IList<DynamicPropertyValue> dynamicProperties, IHasDynamicProperties entity)
        {
            if (dynamicProperties?.Any() ?? false)
            {
                return _dynamicPropertyUpdater.UpdateDynamicPropertyValues(entity, dynamicProperties);
            }
            
            return Task.CompletedTask;
        }
```

2022-05-25 08:03 UTC, Vectorfield4 submitted a review, later dismissed

2022-05-26 16:44 UTC, akak1977 approved these changes

2022-05-26 16:47 UTC, merged