PT-7747: Add contact registration notification
VirtoCommerce/vc-module-profile-experience-api pull request #15
Opened 2022-05-31 13:08 UTC by einlied753

## Description
Add contact registration notification
## References
### QA-test:
### Jira-link: https://virtocommerce.atlassian.net/browse/PT-7747
### Artifact URL:

2022-05-31 13:13 UTC, ksavosteev requested changes

2022-05-31 13:13 UTC, ksavosteev commented on src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterCompanyCommandHandler.cs
> +                await _notificationSender.ScheduleSendNotificationAsync(registerContactNotification);
1. (optional) extract notification creation into methods 
2. only one ScheduleSendNotificationAsync call

2022-05-31 14:16 UTC, getmansky approved these changes

2022-05-31 14:23 UTC, ksavosteev approved these changes

2022-05-31 14:23 UTC, ksavosteev commented on src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterCompanyCommandHandler.cs
> +        protected virtual async Task<EmailNotification> RegisterCompanyNotificationAsync(RegisterCompanyResult result, Store store)
GetRegisterCompanyNotificationAsync

2022-05-31 14:23 UTC, ksavosteev commented on src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterCompanyCommandHandler.cs
> +        protected virtual async Task<EmailNotification> RegisterContactNotificationAsync(RegisterCompanyResult result, Store store)
GetRegisterContactNotificationAsync

2022-06-01 12:29 UTC, getmansky approved these changes

2022-06-01 12:34 UTC, merged